# check=skip=FromPlatformFlagConstDisallowed

FROM --platform=linux/amd64 debian:bookworm

ARG username="dev"

RUN \
	sed -i '/PS1.*\\\$/s/\\\$/\\n\0/' '/etc/skel/.bashrc' && \
	useradd "${username}" -ms '/bin/bash'

RUN \
	apt-get update && \
	apt-get -y dist-upgrade && \
	apt-get -y autopurge

RUN \
	apt-get -y install locales && \
	sed -i '/en_US.UTF-8/s/^# //g' '/etc/locale.gen' && \
	locale-gen

ENV LANG="en_US.UTF-8"
ENV LANGUAGE="en_US:en"
ENV LC_ALL="en_US.UTF-8"

RUN \
	apt-get -y install \
		curl

RUN \
	curl -L "https://go.dev/dl/$(curl -s 'https://go.dev/VERSION?m=text' | head -n1).linux-amd64.tar.gz" | tar -xzC '/usr/local' && \
	echo 'export PATH="$PATH:/usr/local/go/bin"' > '/etc/profile.d/golang.sh'

RUN \
	apt-get -y install \
		git \
		gnupg \
		less \
		man \
		openssh-client \
		patch \
		vim

USER "${username}"
